apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z postgres-db 5432; do echo "Waiting for DB"; sleep 20; done']